import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
	{
		ignores: [
			'dist', // autogenerated by Nuxt
			'.output', // autogenerated by Nuxt
			'.nuxt', // autogenerated by Nuxt
			'node_modules',
			'prismicio-types.d.ts',
		],
	},
)
