// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client'

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] }

type PickContentRelationshipFieldData<
	TRelationship extends
	| prismic.CustomTypeModelFetchCustomTypeLevel1
	| prismic.CustomTypeModelFetchCustomTypeLevel2
	| prismic.CustomTypeModelFetchGroupLevel1
	| prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<
		string,
		| prismic.AnyRegularField
		| prismic.GroupField
		| prismic.NestedGroupField
		| prismic.SliceZone
	>,
	TLang extends string,
>
	// Content relationship fields
= {
		[TSubRelationship in Extract<
			TRelationship['fields'][number],
			prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship['id']]: ContentRelationshipFieldWithData<
			TSubRelationship['customtypes'],
			TLang
		>
	} // Group
	& {
		[TGroup in Extract<
			TRelationship['fields'][number],
			| prismic.CustomTypeModelFetchGroupLevel1
			| prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup['id']]: TData[TGroup['id']] extends prismic.GroupField<
			infer TGroupData
		>
			? prismic.GroupField<
				PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
			>
			: never
	} // Other fields
	& {
		[TFieldKey in Extract<
			TRelationship['fields'][number],
			string
		>]: TFieldKey extends keyof TData ? TData[TFieldKey] : never
	}

type ContentRelationshipFieldWithData<
	TCustomType extends
	| readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
	| readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string,
> = {
	[ID in Exclude<
		TCustomType[number],
		string
	>['id']]: prismic.ContentRelationshipField<
		ID,
		TLang,
		PickContentRelationshipFieldData<
			Extract<TCustomType[number], { id: ID }>,
			Extract<prismic.Content.AllDocumentTypes, { type: ID }>['data'],
			TLang
		>
	>
}[Exclude<TCustomType[number], string>['id']]

type AboutPageDocumentDataSlicesSlice = ContactSliceSlice | SimpleTextSliceSlice

/**
 * Content for About Page documents
 */
interface AboutPageDocumentData {
	/**
	 * Title field in *About Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *About Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * Image field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Slice Zone field in *About Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice> /**
	 * Meta Title field in *About Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: about_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *About Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: about_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *About Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: about_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * About Page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<
		Simplify<AboutPageDocumentData>,
		'about_page',
		Lang
	>

type ArchivePageDocumentDataSlicesSlice
	= | ContactSliceSlice
		| SimpleTextSliceSlice

/**
 * Content for Archive Page documents
 */
interface ArchivePageDocumentData {
	/**
	 * Title field in *Archive Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: archive_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *Archive Page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: archive_page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * Image field in *Archive Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: archive_page.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Slice Zone field in *Archive Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: archive_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ArchivePageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Archive Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: archive_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Archive Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: archive_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Archive Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: archive_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Archive Page document from Prismic
 *
 * - **API ID**: `archive_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ArchivePageDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<
		Simplify<ArchivePageDocumentData>,
		'archive_page',
		Lang
	>

/**
 * Item in *Home page → media*
 */
export interface HomePageDocumentDataMediaItem {
	/**
	 * image field in *Home page → media*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.media[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * video embed field in *Home page → media*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.media[].video_embed
	 * - **Documentation**: https://prismic.io/docs/fields/embed
	 */
	video_embed: prismic.EmbedField
}

type HomePageDocumentDataSlicesSlice
	= | SimpleTextSliceSlice
		| MediaSliceSlice
		| ProjectFeedSliceSlice
		| ContactSliceSlice

/**
 * Content for Home page documents
 */
interface HomePageDocumentData {
	/**
	 * Title field in *Home page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *Home page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * media field in *Home page*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.media[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	media: prismic.GroupField<Simplify<HomePageDocumentDataMediaItem>>

	/**
	 * Slice Zone field in *Home page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Home page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: home_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Home page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: home_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Home page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: home_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Home page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<
		Simplify<HomePageDocumentData>,
		'home_page',
		Lang
	>

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
	/**
	 * Title field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Links field in *Menu*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.links
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	links: prismic.Repeatable<
		prismic.LinkField<string, string, unknown, prismic.FieldState, never>
	>
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, 'menu', Lang>

type ProjectListingPageDocumentDataSlicesSlice
	= | SimpleTextSliceSlice
		| ContactSliceSlice

/**
 * Content for Project listing page documents
 */
interface ProjectListingPageDocumentData {
	/**
	 * Title field in *Project listing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_listing_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *Project listing page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_listing_page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * Image field in *Project listing page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_listing_page.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Slice Zone field in *Project listing page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_listing_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ProjectListingPageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Project listing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: project_listing_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Project listing page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: project_listing_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Project listing page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_listing_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Project listing page document from Prismic
 *
 * - **API ID**: `project_listing_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectListingPageDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<
		Simplify<ProjectListingPageDocumentData>,
		'project_listing_page',
		Lang
	>

type ProjectPageDocumentDataSlicesSlice = MediaSliceSlice | SimpleTextSliceSlice

/**
 * Content for Project page documents
 */
interface ProjectPageDocumentData {
	/**
	 * Title field in *Project page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *Project page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.content
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField

	/**
	 * Image field in *Project page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>

	/**
	 * Client field in *Project page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.client
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	client: prismic.KeyTextField

	/**
	 * Archived field in *Project page*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: project_page.archived
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	archived: prismic.BooleanField

	/**
	 * Publication date field in *Project page*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: Date utilisée pour l'ordre d'affichage
	 * - **API ID Path**: project_page.publication_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	publication_date: prismic.DateField

	/**
	 * Creation date field in *Project page*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.creation_date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/date
	 */
	creation_date: prismic.DateField

	/**
	 * Credits field in *Project page*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.credits
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	credits: prismic.RichTextField

	/**
	 * links field in *Project page*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.links
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	links: prismic.Repeatable<
		prismic.LinkField<
			string,
			string,
			unknown,
			prismic.FieldState,
			'Primary' | 'Secondary'
		>
	>

	/**
	 * Slice Zone field in *Project page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<ProjectPageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Project page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: project_page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField

	/**
	 * Meta Description field in *Project page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: project_page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField

	/**
	 * Meta Image field in *Project page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	meta_image: prismic.ImageField<never>
}

/**
 * Project page document from Prismic
 *
 * - **API ID**: `project_page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectPageDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithUID<
		Simplify<ProjectPageDocumentData>,
		'project_page',
		Lang
	>

/**
 * Item in *settings → Socials*
 */
export interface SettingsDocumentDataSocialsItem {
	/**
	 * Label field in *settings → Socials*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField

	/**
	 * External url field in *settings → Socials*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].external_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	external_url: prismic.KeyTextField

	/**
	 * Icon field in *settings → Socials*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[].icon
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	icon: prismic.SelectField<
		| 'instagram'
		| 'facebook'
		| 'x'
		| 'tiktok'
		| 'vimeo'
		| 'behance'
		| 'youtube'
		| 'linkedin'
	>
}

/**
 * Content for settings documents
 */
interface SettingsDocumentData {
	/**
	 * Site name field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mon site
	 * - **API ID Path**: settings.site_name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	site_name: prismic.KeyTextField

	/**
	 * Email field in *settings*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.email
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField

	/**
	 * Socials field in *settings*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.socials[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	socials: prismic.GroupField<Simplify<SettingsDocumentDataSocialsItem>>
}

/**
 * settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string>
	= prismic.PrismicDocumentWithoutUID<
		Simplify<SettingsDocumentData>,
		'settings',
		Lang
	>

export type AllDocumentTypes
	= | AboutPageDocument
		| ArchivePageDocument
		| HomePageDocument
		| MenuDocument
		| ProjectListingPageDocument
		| ProjectPageDocument
		| SettingsDocument

/**
 * Item in *ContactSlice → Default → Primary → Body*
 */
export interface ContactSliceSliceDefaultPrimaryBodyItem {
	/**
	 * Title field in *ContactSlice → Default → Primary → Body*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.body[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Content field in *ContactSlice → Default → Primary → Body*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.body[].content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField
}

/**
 * Primary content in *ContactSlice → Default → Primary*
 */
export interface ContactSliceSliceDefaultPrimary {
	/**
	 * Spacing field in *ContactSlice → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: contact_slice.default.primary.spacing
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	spacing: prismic.SelectField<
		'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl',
		'filled'
	>

	/**
	 * Title field in *ContactSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Body field in *ContactSlice → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: contact_slice.default.primary.body[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	body: prismic.GroupField<Simplify<ContactSliceSliceDefaultPrimaryBodyItem>>
}

/**
 * Default variation for ContactSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ContactSliceSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *ContactSlice*
 */
type ContactSliceSliceVariation = ContactSliceSliceDefault

/**
 * ContactSlice Shared Slice
 *
 * - **API ID**: `contact_slice`
 * - **Description**: ContactSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceSlice = prismic.SharedSlice<
	'contact_slice',
	ContactSliceSliceVariation
>

/**
 * Item in *MediaSlice → Default → Primary → columns*
 */
export interface MediaSliceSliceDefaultPrimaryColumnsItem {
	/**
	 * Embed video field in *MediaSlice → Default → Primary → columns*
	 *
	 * - **Field Type**: Embed
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_slice.default.primary.columns[].embed
	 * - **Documentation**: https://prismic.io/docs/fields/embed
	 */
	embed: prismic.EmbedField

	/**
	 * Image field in *MediaSlice → Default → Primary → columns*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_slice.default.primary.columns[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>
}

/**
 * Primary content in *MediaSlice → Default → Primary*
 */
export interface MediaSliceSliceDefaultPrimary {
	/**
	 * Spacing field in *MediaSlice → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: media_slice.default.primary.spacing
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	spacing: prismic.SelectField<
		'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl',
		'filled'
	>

	/**
	 * columns field in *MediaSlice → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media_slice.default.primary.columns[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	columns: prismic.GroupField<
		Simplify<MediaSliceSliceDefaultPrimaryColumnsItem>
	>
}

/**
 * Default variation for MediaSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MediaSliceSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *MediaSlice*
 */
type MediaSliceSliceVariation = MediaSliceSliceDefault

/**
 * MediaSlice Shared Slice
 *
 * - **API ID**: `media_slice`
 * - **Description**: MediaSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaSliceSlice = prismic.SharedSlice<
	'media_slice',
	MediaSliceSliceVariation
>

/**
 * Item in *ProjectFeedSlice → Default → Primary → Custom projects*
 */
export interface ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem {
	/**
	 * Project field in *ProjectFeedSlice → Default → Primary → Custom projects*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_feed_slice.default.primary.custom_projects[].project
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	project: prismic.ContentRelationshipField<'project_page'>
}

/**
 * Primary content in *ProjectFeedSlice → Default → Primary*
 */
export interface ProjectFeedSliceSliceDefaultPrimary {
	/**
	 * Spacing field in *ProjectFeedSlice → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_feed_slice.default.primary.spacing
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	spacing: prismic.SelectField<
		'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl'
	>

	/**
	 * Title field in *ProjectFeedSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_feed_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * Automatic projects length field in *ProjectFeedSlice → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: Default is 3
	 * - **API ID Path**: project_feed_slice.default.primary.automatic_projects_length
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	automatic_projects_length: prismic.NumberField

	/**
	 * Custom projects field in *ProjectFeedSlice → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_feed_slice.default.primary.custom_projects[]
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	custom_projects: prismic.GroupField<
		Simplify<ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem>
	>

	/**
	 * Link field in *ProjectFeedSlice → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project_feed_slice.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>
}

/**
 * Default variation for ProjectFeedSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectFeedSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProjectFeedSliceSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *ProjectFeedSlice*
 */
type ProjectFeedSliceSliceVariation = ProjectFeedSliceSliceDefault

/**
 * ProjectFeedSlice Shared Slice
 *
 * - **API ID**: `project_feed_slice`
 * - **Description**: ProjectFeedSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProjectFeedSliceSlice = prismic.SharedSlice<
	'project_feed_slice',
	ProjectFeedSliceSliceVariation
>

/**
 * Primary content in *SimpleTextSlice → Default → Primary*
 */
export interface SimpleTextSliceSliceDefaultPrimary {
	/**
	 * Spacing field in *SimpleTextSlice → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: none
	 * - **API ID Path**: simple_text_slice.default.primary.spacing
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	spacing: prismic.SelectField<
		'none' | 'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'xxl',
		'filled'
	>

	/**
	 * Title field in *SimpleTextSlice → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: simple_text_slice.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField

	/**
	 * content field in *SimpleTextSlice → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: simple_text_slice.default.primary.content
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	content: prismic.RichTextField
}

/**
 * Default variation for SimpleTextSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleTextSliceSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SimpleTextSliceSliceDefaultPrimary>,
	never
>

/**
 * Slice variation for *SimpleTextSlice*
 */
type SimpleTextSliceSliceVariation = SimpleTextSliceSliceDefault

/**
 * SimpleTextSlice Shared Slice
 *
 * - **API ID**: `simple_text_slice`
 * - **Description**: SimpleTextSlice
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SimpleTextSliceSlice = prismic.SharedSlice<
	'simple_text_slice',
	SimpleTextSliceSliceVariation
>

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig,
		): prismic.Client<AllDocumentTypes>
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig,
		): prismic.WriteClient<AllDocumentTypes>
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>
	}

	namespace Content {
		export type {
			AboutPageDocument,
			AboutPageDocumentData,
			AboutPageDocumentDataSlicesSlice,
			ArchivePageDocument,
			ArchivePageDocumentData,
			ArchivePageDocumentDataSlicesSlice,
			HomePageDocument,
			HomePageDocumentData,
			HomePageDocumentDataMediaItem,
			HomePageDocumentDataSlicesSlice,
			MenuDocument,
			MenuDocumentData,
			ProjectListingPageDocument,
			ProjectListingPageDocumentData,
			ProjectListingPageDocumentDataSlicesSlice,
			ProjectPageDocument,
			ProjectPageDocumentData,
			ProjectPageDocumentDataSlicesSlice,
			SettingsDocument,
			SettingsDocumentData,
			SettingsDocumentDataSocialsItem,
			AllDocumentTypes,
			ContactSliceSlice,
			ContactSliceSliceDefaultPrimaryBodyItem,
			ContactSliceSliceDefaultPrimary,
			ContactSliceSliceVariation,
			ContactSliceSliceDefault,
			MediaSliceSlice,
			MediaSliceSliceDefaultPrimaryColumnsItem,
			MediaSliceSliceDefaultPrimary,
			MediaSliceSliceVariation,
			MediaSliceSliceDefault,
			ProjectFeedSliceSlice,
			ProjectFeedSliceSliceDefaultPrimaryCustomProjectsItem,
			ProjectFeedSliceSliceDefaultPrimary,
			ProjectFeedSliceSliceVariation,
			ProjectFeedSliceSliceDefault,
			SimpleTextSliceSlice,
			SimpleTextSliceSliceDefaultPrimary,
			SimpleTextSliceSliceVariation,
			SimpleTextSliceSliceDefault,
		}
	}
}
